Development
ElijahCode/Game-of-Life-FP pull request #1
Opened 2021-04-17 17:54 UTC by ElijahCode

2021-04-21 17:20 UTC, AntiHero requested changes

2021-04-21 17:20 UTC, AntiHero commented on package.json
> +    "build": "webpack",
в чём смысл наличия такого скрипта?

2021-04-21 17:20 UTC, AntiHero commented on src/ts/gameLogicFunc/changeSizeofField/changeSizeofField.test.ts
> +  const newState: number[][] = changeSizeofField(width, heigth, state);
если changeSizeofField возвращает тебе тип `number[][]`, то при инициализации переменной его указывать не надо, ts сам выведет тебе нужный тип

2021-04-21 17:20 UTC, AntiHero commented on src/ts/gameLogicFunc/changeSizeofField/changeSizeofField.test.ts
> +    expect(
поле может поменять своё состояние таким образом, чтобы сумма  значений всех ячеек оставалась одинаковой? если да, то смысл в этом тесте?

2021-04-21 17:20 UTC, AntiHero commented on src/ts/gameLogicFunc/createGameField/createGameField.test.ts
> +  const widht: number = Math.floor(1 + Math.random() * 100);
width

2021-04-21 17:20 UTC, AntiHero commented on src/ts/gameLogicFunc/changeSizeofField/changeSizeofField.ts
> +    row.map((cell: number, x) => {
` row.map((_, x) => {`

2021-04-21 17:20 UTC, AntiHero commented on src/ts/gameLogicFunc/getNextGeneration/getNextGeneration.ts
> +        cellState = 1;
if что-то - cellState = 1, else if что-то cellState = 1, объеденить?

2021-04-21 17:20 UTC, AntiHero commented on src/ts/index.ts
> +    BASIC_GAME_FIELD_WIDTH,
а запихнуть их в твои инпуты?

2021-04-21 17:26 UTC, AntiHero commented
- поправить инпуты, добавить в них дефолтные значения, сделать проверки на ввод некорректных значений
- сделать очистку Interval, когда игра заканчивается
- реализовать кейс завершения игры при потворяющихся паттернах

2021-05-01 06:55 UTC, ElijahCode commented on package.json
> +    "build": "webpack",
Иногда в случае внесения изменения при работающем сервере ломается построение проекта "на лету"..Поэтому в таких случаях билд делаю вручную.

2021-05-01 06:56 UTC, ElijahCode commented on src/ts/gameLogicFunc/changeSizeofField/changeSizeofField.test.ts
> +  const newState: number[][] = changeSizeofField(width, heigth, state);
Исправлено

2021-05-01 06:57 UTC, ElijahCode commented on src/ts/gameLogicFunc/changeSizeofField/changeSizeofField.test.ts
> +    expect(
убрал проверку

2021-05-01 06:59 UTC, ElijahCode commented on src/ts/gameLogicFunc/createGameField/createGameField.test.ts
> +  const widht: number = Math.floor(1 + Math.random() * 100);
Исправлено

2021-05-01 07:00 UTC, ElijahCode commented on src/ts/gameLogicFunc/changeSizeofField/changeSizeofField.ts
> +    row.map((cell: number, x) => {
исправлено

2021-05-01 07:06 UTC, ElijahCode commented on src/ts/gameLogicFunc/getNextGeneration/getNextGeneration.ts
> +        cellState = 1;
Объединил

2021-05-01 07:26 UTC, ElijahCode commented on src/ts/index.ts
> +    BASIC_GAME_FIELD_WIDTH,
Сделано

2021-05-01 14:00 UTC, AntiHero commented on src/ts/css/style.css
> +.button-reset {
можно было бы поиграться со стилями, чтобы кнопка в итоге оказалась по середине поля снизу

2021-05-01 14:00 UTC, AntiHero commented on src/ts/handlersFunc/onInputChange/onInputChange.ts
> +          : -Number(element.target.value);
да, у нас будет положительное в итоге число столбцов, но  target.value то всё равно останется отрицательным числом?

2021-05-01 14:00 UTC, AntiHero commented on src/ts/index.ts
> +        ID = null;
зачем null?) clearInterval() возвращает undefined и ты этим сразу можешь воспользоваться

2021-05-01 14:00 UTC, AntiHero commented on tsconfig.json
> +{
какой-то маленький tsconfig получился, можешь сделать базовый, который будет основой для всех твоих домашек, в котром будут всякие полезные и нужные штуки как "noImplicitAny" и т.д., можешь посмотреть и взять себе как вариант какой-то базовый конфиг из https://github.com/tsconfig/bases/

2021-05-01 14:00 UTC, AntiHero commented on src/ts/utils/utils.ts
> +    <body class = "body">
body внутри body?) так не получится во-первых, во-вторых (хоть это и не критично) в данном случае у итогового body не будет класса .body

2021-05-01 14:00 UTC, AntiHero commented on src/ts/gameLogicFunc/getNumbAliveCell/getNumbAliveCell.ts
> +        sum += 1;
тут можно попробовать в одну строку написать эту функцию, т.е. у тебя есть матрица, мы можем её привести к строке с помощью метода `.toString()`, затем из этой строки сделать массив и потом с помощью reduce найти его сумму, т.к. клетки у тебя в двух состояниях 0 или 1, то в итоге и получается сумма живых клеток и есть их кол-во

2021-05-02 06:45 UTC, ElijahCode commented on src/ts/css/style.css
> +.button-reset {
Сделано

2021-05-02 07:06 UTC, ElijahCode commented on src/ts/handlersFunc/onInputChange/onInputChange.ts
> +          : -Number(element.target.value);
Исправлено. Отрицательное число в инпуте теперь сразу преобразуется к положительному.

2021-05-02 07:10 UTC, ElijahCode commented on src/ts/index.ts
> +        ID = null;
Исправлено

2021-05-02 08:01 UTC, ElijahCode commented on tsconfig.json
> +{
Взял базовый вариант, который представлен по ссылке. Оттуда для этого проекта выкинул strict, так как под его требования придется перелопачивать типизацию всего проекта. В будущем буду его использовать.

2021-05-02 08:04 UTC, ElijahCode commented on src/ts/utils/utils.ts
> +    <body class = "body">
если обратишь внимание, я его использую только в тестах, и в тестах всегда есть присваивание document.body = element;

Проблемы как я считаю нет. Но соглашусь, что лучше бы было его запихнуть в отдельный div.

2021-05-02 08:26 UTC, ElijahCode commented on src/ts/gameLogicFunc/getNumbAliveCell/getNumbAliveCell.ts
> +        sum += 1;
Идея хорошая, но эта функция ищет кол-во живых клеток не во всем игровом поле, а в его куске рамзером 3х3, в центре этого куска живая клетка, для которой и подсчитывается количество живых клеток в соседних полях. 
И вот как раз основной проблемой и будет определение индексов соседних полей в этой единой строке. И по итогу, как мне кажется, функция будет столь же "многословна", как и текущая реализация.
На досуге попробую реализовать, но сейчас этим заниматься, я думаю, не стоит

2021-05-02 09:27 UTC, AntiHero commented on src/ts/utils/utils.ts
> +    <body class = "body">
да дело не в отдельном диве) а в том что тебе оборачивающий `<body class = "body">` не нужен, не имеет смысла он, ты в боди тэг не можешь вставить ещё один боди

2021-05-26 03:24 UTC, merged